const products = [
    {
      id: 1,
      name: "Produit 1",
      description: "chocolat blanc",
      price: 3,
      photo: "photo/tablette_blanc.jpg",
      quantité: 0,
    },
    {
      id: 2,
      name: "Produit 2",
      description: "chocolat lait ",
      price: 12.99,
      photo: "photo/tablette_lait.jpg",
      quantité: 0,
    },
    {
      id: 3,
      name: "Produit 3",
      description: "chocolat noir",
      price: 3,
      photo: "photo/tablette_noir.jpg",
      quantité: 0,
    },
    {
      id: 4,
      name: "Produit 4",
      description: "pate à tartiner blanc",
      price: 6.99,
      photo: "photo/chocolat-blanc.jpg",
      quantité: 0,
    },
    {
      id: 5,
      name: "Produit 5",
      description: "pate à tartiner lait",
      price: 14.99,
      photo: "photo/chocolat-lait.jpg",
      quantité: 0,
    },
    {
      id: 6,
      name: "Produit 6",
      description: "pate à tartiner noir",
      price: 19.99,
      photo: "photo/chocolat-noir.jpg",
      quantité: 0,
    },
  ];
